### ISSUE TITLE
Some URLs in the website give 404 Not Found 

### ISSUE THREAD

**Issue by malta895** [soumya92/barista#177]
I was following the guide [Customizing Barista](https://barista.run/docs/customising), and I get 404 errors on the `curl`s commands. In particular these 2 links are down:

* https://git.io/Je90h
* https://git.io/fA7iZ

They point to master branch of this repository, which has been renamed to main, it seems this is the reason they don't work.

**Comment by malta895** [comment]
I realized the man pages are on another branch. I added a PR, #178, it should fix it.

**Comment by soumya92** [comment]
Fixed in #178. Thanks for spotting and fixing this.
