### ISSUE TITLE
Help with getting started.

### ISSUE THREAD

**Issue by annata83** [soumya92/barista#194]
terminal output by executing the sample-bar.go:

```
./sample-bar.go: line 2: //: Is a directory
./sample-bar.go: line 3: //: Is a directory
./sample-bar.go: line 4: syntax error near unexpected token `('
./sample-bar.go: line 4: `// Licensed under the Apache License, Version 2.0 (the "License");'
 
```
i3bar error:
`status command not found or is missing a library dependency ( exit 127 )`

barista execution in terminal output:
```

panic: Could not setup oauth token encryption: failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'

goroutine 1 [running]:
main.main()
        /home/runner/work/barista/barista/samples/sample-bar/sample-bar.go:283 +0x2a8e

```

Arch Linux user running from:
```
/.config/barista/barista
/.config/barista/sample-bar.go
```
executing from i3config like so:

`status_command exec ~/.config/barista/sample-bar.go`

**Comment by thomasschuiki** [comment]
Hi,

I am unsure how your complete setup looks like, but you need to compile the sample-bar.go file to a binary before adding it to the i3 config.

build
``` bash
go build -o <your-build-dir>/samplebar
```

i3wm config
```
bar {
        status_command exec <your-build-dir>/samplebar
...
}
```

Hope this helps.

**Comment by soumya92** [comment]
> `status_command exec ~/.config/barista/sample-bar.go`

Yeah, as pointed out by @thomasschuiki, the go file needs to be compiled before it can be used.

> `failed to unlock correct collection`

This is interesting. I haven't seen this specific error before, but this is coming from oauth's use of the system keychain. You can either remove all the oauth code (so no gmail, gsuite calendar, or github) and compile the bar yourself, or you could try using your system's password manager (seahorse/gnome keyring, kde wallet, something else) to see if there's something unusual going on. See https://github.com/zalando/go-keyring#linux for docs from the library I use.

**Comment by annata83** [comment]
Apparently I do not have go installed and wont installed anyway is to big 560 MB After installation...
Thanks anyways.
