### ISSUE TITLE
Media - default to first available player; document how to get player name

### ISSUE THREAD

**Issue by glebtv** [soumya92/barista#20]
It is not obvious that you need mrpis player name (and also maybe an mrpis plugin for a player)
It would be nice to use first available player, like playerctl does for example

Minimal documentation example:

	// You need to know your dbus\mrpis player name
	// find your player name via playerctl -l
	// https://github.com/acrisci/playerctl
	// for deadbeef use this plugin:
	// https://aur.archlinux.org/packages/deadbeef-mpris2-plugin/
	return media.New("DeaDBeeF").OutputFunc(mediaFormatFunc)

dbus list players: 
https://github.com/acrisci/playerctl/blob/master/playerctl/playerctl-cli.c#L46
https://github.com/acrisci/playerctl/issues/47

**Comment by soumya92** [comment]
This makes a lot of sense. `playerctl -l` seems great, although you do need to have the player currently running. In the module documentation/wiki page, we could also list common players that support mpris, along with a link to their plugin if they need one.

I'll definitely keep this in mind when I start writing docs on the individual modules.

**Comment by soumya92** [comment]
Docs are now live, and the [media module docs](https://barista.run/modules/media) call out `playerctl`
