### ISSUE TITLE
Binaries not being attached to automatic releases

### ISSUE THREAD

**Issue by macobo** [soumya92/barista#202]
Instructions over at https://barista.run/ are now out of date, `download sample-bar` and curl command lead to a 404.

**Comment by soumya92** [comment]
Fixed for now. Looks like the autorelease workflow is leaving binaries in the draft phase. Manually published for now, while I look into what broke in the release process

**Comment by soumya92** [comment]
Huh. Looks like it was a transient issue. The newest CI run successfully uploaded the binaries with no changes to the workflow file.
