### ISSUE TITLE
Add a changelog \ upgrade guide

### ISSUE THREAD

**Issue by glebtv** [soumya92/barista#24]
Add a changelog \ upgrade guide

I have updated [my config](https://github.com/glebtv/custom_barista) to current version of barista and I have to say it wasn't straightforward, had to read source code to do it

The most non-obvious thing is that I can't instantiate bar.Output now (since it's an interface) and had to make my own type for it, which should not work like this I think

https://github.com/glebtv/custom_barista/blob/master/kbdlayout/module.go#L37

**Comment by glebtv** [comment]
Also, had non-debuggable segfaults with previous media example config (found that it was media by disabling plugins one by one only)
here https://github.com/glebtv/custom_barista/blob/31344fbc7cde088d4067a74a69c56baccfa259be/music/music.go#L40

**Comment by soumya92** [comment]
Logging is done and documented. The API is ... relatively stable. At least there exists a stable-api sample that should not see any changes, only additions as more of the APIs become stable.
