### ISSUE TITLE
/sys/class/hwmon/ temperature readings

### ISSUE THREAD

**Issue by WGH-** [soumya92/barista#247]
Existng `cputemp` module only supports `/sys/class/thermal/%s/temp` paths.

In Linux, there's also `/sys/class/hwmon/`. For example, on my system, `hwmon0` is the CPU, `hwmon1` is motherboard sensors, and `hwmon2` is the GPU:
```
% cat /sys/class/hwmon/hwmon0/{name,temp*_{label,input}}
k10temp
Tctl
Tdie
Tccd1
Tccd2
43875
43875
32250
32250
% cat /sys/class/hwmon/hwmon2/{name,temp*_{label,input}}
amdgpu
edge
junction
mem
40000
40000
42000
```

In contrast, `/sys/class/thermal/*` on my system has only `cooling_device%d` files for each CPU core without `temp` data (without any useful data, in fact).

Solving this would address what #77 attempted to do, but more generically.

**Comment by soumya92** [comment]
Looks great! Feel free to send a PR if you have this working or really want it quickly :)

**Comment by WGH-** [comment]
This seems easy enough. I'll likely do relatively soon, but not right now.
