### ISSUE TITLE
Glyph fonts not showing correctly

### ISSUE THREAD

**Issue by foxhoundsk** [soumya92/barista#305]
Hi, I'm using `sample-bar`, and just got Font-Awesome installed.

I found that the glyph (`fa-camera`) is showing its raw code (I'm not sure what's its terminology), as shown below:
![image](https://user-images.githubusercontent.com/19415202/188297552-ec7a1158-0b89-48b8-93d1-1387f8a5920b.png)

I have performed `fc-cache -fv` and the log shows that the font is installed.

What could be wrong to make the glyph not showing properly?

Thanks!

**Comment by soumya92** [comment]
Most probably this is a mismatch between the font version you have installed and what the sample bar was built with.

I know font awesome changed versions recently and I haven't updated yet,  so maybe you need to install an older font file, or build sample-bar locally to match code points

**Comment by foxhoundsk** [comment]
Thanks for the reply!

By code points do you mean the following?
```
fontawesome.Load(home("Github/Font-Awesome"))
```
If I change the icon name, for example, from `fa-camera` to `far-camera`, there would have no any icons (even the raw code).

For building the example bar, I use:
```
./build.sh -o ~/bin/mybar -i samples/sample-bar/sample-bar.go
```
And then use `mod+shift+r` to restart i3 to reload i3status.

For making symbolic link to the font, I use:
```
ln -s "$PWD/Font-Awesome/otfs/Font Awesome 6 Brands-Regular-400.otf" ~/.fonts/
```
which is one of the three commands making the sym links for Font-Awesome. And the `pwd` is the directory where repo Font-Awesome exists. Also, `fc-cache -fv` is performed afterwards.

What could be wrong? Please feel free to ask other information if needed.
Thanks!

**Comment by soumya92** [comment]
Yeah, that is the code points file. I agree that it seems to be loaded because you are seeing some characters, if that had failed you wouldn't get any icons. Have you symlinked all the otfs from the font awesome folder? Maybe the code points are in one file but the glyphs are spread across multiple files...

**Comment by foxhoundsk** [comment]
Sorry for the late reply.

I've tried symlink-ing all possible fonts under the repository (in addition to `Font Awesome 6 ***.otf` ones, `fa-***.ttf`-ish fonts are also added to the font directory). Besides, I've also tried putting the fonts to `/usr/share/fonts/Font-Awesome` and assured that `fc-cache` found the fonts during generation of font cache.

Sadly, none of these aid the wrong-displaying issue. Do you have any idea what could be the cause? Would it be possible that the problem is rooted from the pango package?

Thanks!

**Comment by soumya92** [comment]
Ahhh I missed the fact that you're using Font Awesome 6. Currently the fontawesome icons package only supports v5 :(
You'll need to symlink the v5 fonts, not the v6 ones, to see them load in the bar. There is a fork somewhere that supports v6 but hasn't yet been integrated here (https://github.com/soumya92/barista/issues/201#issuecomment-1207703134)

**Comment by foxhoundsk** [comment]
Thank you!! The glyphs are now rendered properly.
