### ISSUE TITLE
EOF error on locking the screen

### ISSUE THREAD

**Issue by ajeetdsouza** [soumya92/barista#368]
Somehow, every time I lock the screen, barista exits with an `EOF` error.

- This happens even when I remove all the modules and keep an empty bar
- This error seems unique to barista - it does not happen with `i3status`
- The error only happens when I'm actually using it as a `status_command` - if I run it in a terminal and lock the screen, there is no error
- I tested with xsecurelock and i3lock and the same error occurs

```go
if err := barista.Run(); err != nil {
    log.Fatal("error in barista: ", err.Error())
}
```

Output:

```
2023/04/02 12:24:33 error in barista: EOF
```

Output of `baristadebuglog`:

```
2023/04/02 14:17:42 id.go:344 (bar:logging.Register) Could not find format in mod:internal/temperature.Module#0</sys/class/thermal/thermal_zone6/temp>
2023/04/02 14:17:42 id.go:344 (bar:logging.Register) Could not find impl in mod:volume.Module#0
2023/04/02 14:17:42 id.go:344 (bar:logging.Register) Could not find format in mod:battery.Module#0
2023/04/02 14:17:42 barista.go:182 (barista%2erun.Run) Bar started
2023/04/02 14:17:42 barista.go:373 (barista%2erun.i3Bar.resume) Bar resumed
2023/04/02 14:17:48 barista.go:360 (barista%2erun.i3Bar.pause) Bar paused
```

It also randomly crashes on other occasions with the same error. Here's a different error I saw recently:

```
2023/04/02 16:07:46 error in barista: stdin exhausted
```

Version information:

```
OS: Pop!_OS 22.04 LTS
i3: v4.22
barista: v0.0.0-20230330190245-328cd67e2c27
```

**Comment by soumya92** [comment]
Could this be https://github.com/i3/i3/issues/1741?

You can try adding `.SuppressSignals(true)` to your barista instance to avoid pause/resume handling if the solution there does not work for you.

**Comment by ajeetdsouza** [comment]
Using `status_command exec xbar` appears to fix it. Thank you!

P.S. `barista` is a lovely piece of software, thank you for making it!
