### ISSUE TITLE
Replace Weather Underground with AccuWeather

### ISSUE THREAD

**Issue by soumya92** [soumya92/barista#45]
WU no longer offers API keys for personal use, while AccuWeather seems happy to do so.

**Comment by Oshuma** [comment]
There's also https://www.apixu.com/ that I've found and am planning on writing a Provider for my own use.  I can fork and submit a PR once I've finished it.

**Comment by soumya92** [comment]
Looks pretty good. The limits seem high enough for individual use.
Feel free to send a PR whenever you're done. Thanks!

**Comment by soumya92** [comment]
APIXU seems like a good enough replacement for Weather Underground, so marking this as closed.
I'll gladly accept a PR for adding AccuWeather, but the choices offered now seem sufficient.
