### ISSUE TITLE
Add go.mod

### ISSUE THREAD

**Issue by GregorioDiStefano** [soumya92/barista#47]
Hi, 

Awesome project, would love to contribute, but, can you vendor the dependencies you are using?
Trying to get master of all dependencies and building fails with: 

```
../../../../../barista.run/pango/icons/fontawesome/fontawesome.go:68:8: undefined: yaml.NewDecoder
# barista.run/pango/icons/typicons
../../../../../barista.run/pango/icons/typicons/typicons.go:53:8: undefined: yaml.NewDecoder
```

**Comment by GregorioDiStefano** [comment]
Fixed by updating global dependencies, but I still think it might be a good idea to use vendoring.

**Comment by soumya92** [comment]
Probably. I'm waiting for the whole "modules" thing to be finalised. Other vendoring solutions require me choosing one, but modules will be baked into the language/tooling, so that's probably the easiest one to use.

I'm surprised yaml broke this way, especially since it comes from gopkg which versions already, but I guess that only highlights the need for some sort of package management within the tooling :)

I'll keep this issue open to track the module migration

**Comment by Oshuma** [comment]
Possibly related or unrelated, but after creating a `go.mod` (using `go mod init`) and building my single bar file (`go build greybox_status.go`), the icons no longer show in my bar (using FontAwesome).  If I remove the `go.mod` file and build without Go 1.11's vendoring, the icons show fine.  Pasted below is output before (go 1.10) and after (go 1.11) vendoring.

Before vendoring (go 1.10):
```
[{"full_text":"\u003cspan alpha='52428'\u003e\u003cspan face='Font Awesome 5 Free' weight='900' fallback='false'\u003e\u003c/span\u003e\u003c/span\u003e\u003cspan size='xx-small'\u003e \u003c/span\u003e\u003cspan alpha='52428'\u003e\u003cspan face='Font Awesome 5 Free' weight='900' fallback='false'\u003e\u003c/span\u003e\u003c/span\u003e","markup":"pango","name":"0"},{"full_text":"\u003cspan alpha='52428'\u003e\u003cspan face='Font Awesome 5 Free' weight='900' fallback='false'\u003e\u003c/span\u003e\u003c/span\u003e\u003cspan size='xx-small'\u003e \u003c/span\u003e\u003cspan alpha='52428'\u003e\u003cspan face='Font Awesome 5 Free' weight='900' fallback='false'\u003e\u003c/span\u003e\u003c/span\u003e","markup":"pango","name":"1"},{"full_text":"\u003cspan alpha='52428'\u003e\u003cspan face='Font Awesome 5 Free' weight='900' fallback='false'\u003e\u003c/span\u003e\u003c/span\u003e\u003cspan size='xx-small'\u003e \u003c/span\u003eFri Dec 14\u003cspan size='xx-small'\u003e \u003c/span\u003e\u003cspan alpha='52428'\u003e\u003cspan weight='900' fallback='false' face='Font Awesome 5 Free'\u003e\u003c/span\u003e\u003c/span\u003e\u003cspan size='xx-small'\u003e \u003c/span\u003e03:38","markup":"pango","name":"2"}]
```

After vendoring (go 1.11):
```
[{"full_text":"\u003cspan alpha='52428'\u003e\u003c/span\u003e\u003cspan size='xx-small'\u003e \u003c/span\u003e\u003cspan alpha='52428'\u003e\u003c/span\u003e","markup":"pango","name":"0"},{"full_text":"\u003cspan alpha='52428'\u003e\u003c/span\u003e\u003cspan size='xx-small'\u003e \u003c/span\u003e\u003cspan alpha='52428'\u003e\u003c/span\u003e","markup":"pango","name":"1"},{"full_text":"\u003cspan alpha='52428'\u003e\u003c/span\u003e\u003cspan size='xx-small'\u003e \u003c/span\u003eFri Dec 14\u003cspan size='xx-small'\u003e \u003c/span\u003e\u003cspan alpha='52428'\u003e\u003c/span\u003e\u003cspan size='xx-small'\u003e \u003c/span\u003e03:35","markup":"pango","name":"2"}]
```

**Comment by soumya92** [comment]
Font Awesome recently re-organised their files.

You might just need to update the local clone of the repo (and symlinks to the otfs) to get the icons to show again. Or you could pin barista.run/pango/icons/fontawesome to b736857f237f6a460e282eeb2df45d29dfd3f8c7 in the mod file.

**Comment by Oshuma** [comment]
@soumya92 Yep, updating local FA repo and symlinks worked.  Thanks!

**Comment by shibumi** [comment]
I would suggest you vendor dependencies with `go.mod`: https://github.com/golang/go/wiki/Modules#gomod

**Comment by soumya92** [comment]
This is still on my radar. I'm waiting for go modules to be stabilised, which looks like 1.13 (https://github.com/golang/go/wiki/Modules).

Once that's done, I will need to find a way for the CI to automatically update the go.mod file when tests pass, so that the versions in go.mod are as close to head as possible, without being broken. That should be the best of both worlds: always compatible but close to latest.
