### ISSUE TITLE
Copyright by Google?

### ISSUE THREAD

**Issue by GregorioDiStefano** [soumya92/barista#48]
Your go files claim to by copyright of Google:

https://github.com/soumya92/barista/blob/master/outputs/group.go#L1

**Comment by soumya92** [comment]
Yes, that is correct. The code I author for this project is owned by my employer.
Do you have concerns about that? I can reach out internally if necessary.

**Comment by soumya92** [comment]
Closing this issue for now, please reopen if you have any further questions/comments.
