### ISSUE TITLE
Support for multiple monitors

### ISSUE THREAD

**Issue by binaryplease** [soumya92/barista#53]
Hi, 

I have been using polybar for a while, but am looking for a replacement because it doesn't support multiple monitors, which annoys me (there are workarounds, but thats just a hack).

Does barista support multiple screens with i3?
If not, how hard would it be to implement? I know some go and would be willing to help.

Cheers,

Pablo

**Comment by Oshuma** [comment]
I run i3 on my desktop with multiple monitors, using a single barista binary (and i3 `bar` configuration).  The output is duplicated on both monitors, which is fine for me.  It should be easy to build two different barista binaries and specify two `bar` configs for i3 as mentioned above.

**Comment by shibumi** [comment]
multi monitor support works as me as expected (the i3bar will get mirrored on both monitors)

**Comment by soumya92** [comment]
I'm going to close this for now. Multiple monitors is currently supported either by mirroring the same binary, or by building two different binaries with different sets of modules.
