### ISSUE TITLE
Bluetooth module

### ISSUE THREAD

**Issue by Oshuma** [soumya92/barista#55]
Any plans to implement a bluetooth module?  I could try taking a stab at it, but I have zero knowledge about bluetooth internals.

**Comment by soumya92** [comment]
Not at the moment. Bluetooth seems pretty interactive, so something equivalent to NetworkManager, but for BT is probably better than a barista module. (i.e., systray icon with interactive menus and popup dialogues)

A connected/disconnected/battery module might make sense, so this can be an FR for a simple status module for a BT device. Talking to blues over DBus is probably the best way to implement this. The API documentation is at https://docs.ubuntu.com/core/en/stacks/bluetooth/bluez/docs/reference/dbus-api

**Comment by Oshuma** [comment]
Yea, a simple status module is what I had in mind.  Shows if receiver on/off, device connected status, etc.  Pairing would still be handled through a systray app.

**Comment by soumya92** [comment]
Sounds good. If you want to take a crack at it, the DBus API is linked above, and base/watchers/dbus should have enough to see it through (including tests).

Otherwise I will take a look after the themes work is done. I don't use any BT devices, so I'll need to dig up a few for testing.

**Comment by Oshuma** [comment]
So I have a very rudimentary way of getting BT adapters/devices info (https://gist.github.com/Oshuma/256024b1a6347c6a352b50c6ff94d307), but I'm not sure how/if I should use the base/watchers/dbus package?  Seems like the only thing that package would be useful for is to get a bus with (base/watchers/)`dbus.System`, which is trivial with the 'godbus/dbus' package.

**Comment by soumya92** [comment]
Take a look at the systemd module for an example. What you have in the gist doesn't need the watcher, but once you add updates to the mix using the watcher will provide instant updates without polling

**Comment by Oshuma** [comment]
Merged in here:  c0445ee4b4f4b9a64e80949e72e8cb0979e21cbf
