### ISSUE TITLE
[battery] battery.Info.PluggedIn() doesn't work as expected

### ISSUE THREAD

**Issue by shibumi** [soumya92/barista#64]
I have the following status:
```
chris motoko ~ 23:38:38 910eecdf master  
❯ acpi -b 
Battery 0: Unknown, 99%
chris motoko ~ 23:38:41 910eecdf master  
❯ acpi -a
Adapter 0: on-line
chris motoko ~ 23:38:51 910eecdf master  
❯ ls /sys/class/power_supply/
AC  BAT0
```

The laptop (Lenovo X220) is docked into a dockingstation. I run the following code:
```
barista.Add(battery.All().Output(func(b battery.Info) bar.Output {
		if b.Status == battery.Disconnected {
			return nil
		}
		if b.Status == battery.Full {
			out := outputs.Text("B: 100%")
			out.Color(colors.Scheme("good"))
			return out
		}
		out := outputs.Textf("B: %d%% %s",
			b.RemainingPct(),
			b.RemainingTime())
		if b.PluggedIn() {
			out.Color(colors.Scheme("good"))
			return out
		}
		if b.Discharging() {
			if b.RemainingPct() < 20 {
				out.Color(colors.Scheme("bad"))
				return out
			} else if b.RemainingPct() < 50 {
				out.Color(colors.Scheme("degraded"))
				return out
			} else {
				out.Color(colors.Scheme("good"))
				return out
			}
		}
		return nil
	}))
```

The function `b.PluggedIn()` returns false although `acpi -a` says that the power adapter is plugged in. 
I run also everytime in the status `b.Discharging ()` although `acpi` returns the status `unknown`. Has this something to do with my docking station?

**Comment by soumya92** [comment]
Interesting. PluggedIn returning true for a docking station is fine with me. Shouldn't be too hard to fix.

The discharging could be explained by the fact that All() does not account for docking stations, so the battery might look like it's being discharged (or unknown), because we see a drain from BAT0 but we skip the input on AC.

I will try to reproduce this with my docking station

**Comment by shibumi** [comment]
cool thanks, currently I always jump into the b.Discharging branch.. I have solved this with setting "good" color when I am over 50%...

**Comment by soumya92** [comment]
Looking into this some more:
- It's not clear that on-line implies the adapter is providing sufficient power. Could we be online but still discharging?
- There's definitely some bad logic for discharging, and it should just be if status == Discharging
- Thinkpads seem to have trouble with acpi, based on some forum threads that I found when researching acpi

I'll fix the discharging check on battery.Info
