### ISSUE TITLE
[netspeed] Add a method to check whether interface is down

### ISSUE THREAD

**Issue by shibumi** [soumya92/barista#65]
It would be nice to have the option to return nil when the interface is down. I have checked the `netspeed` implementation and it looks like you already have something to detect if the interface provides `Rx` and `Tx` values. Currently my i3bar shows the whole netspeed segment for the ethernet interface, although it's down and therefor nothing will be transmitted.

**Comment by soumya92** [comment]
netspeed.Speeds is a simple struct, so nil will not be possible. But I can definitely add a `Connected() bool`, so those who don't want to handle that specially can keep using the current formatting function (which will show 0 for all values), but anyone who wants to (e.g.) hide the output when disconnected will also be able to do that.

**Comment by shibumi** [comment]
awesome thanks!
