### ISSUE TITLE
Mismatch in oauth filename

### ISSUE THREAD

**Issue by soumya92** [soumya92/barista#75]
From #51,

At runtime the module is looking for `accounts.google.com_h4t7vKdZ8bdNUC84tgkAVX4Vc48AEaO3PYBoHQ.json`, but after setup only 
`accounts.google.com_hJH2bG9JCbl58ZDknZDsVqVtwZZ9fzDctHu0pQ.json` exists. Need to debug why this mismatch happens, and how to prevent it.

**Comment by soumya92** [comment]
The random string is a hash with the only inputs being the Client ID and the list of scopes. Both of which are deterministic.

The modules usually accept an oauth config, and call register during construction, while the interactive setup call does not take place until `barista.Run`, so there _should_ be no way to use a config in the module that wasn't already registered. And all registered configs should be initialised during interactive setup.

**Comment by soumya92** [comment]
To debug this some more, could you share the relevant code for the module(s) that use oauth? How are you providing the configuration?

Is it possible that there are two modules that use oauth, one of which is working fine using the file that is present, but the other one is failing with the file not found?

**Comment by danihodovic** [comment]
The code is copied from the sample bar. The changes I've made is to read the OAuth credentials from the environment.

https://gist.github.com/danihodovic/6a9aa65e0da234a0f44c1d406879ca5f

**Comment by soumya92** [comment]
Oh, it looks like you're selecting the Client ID at **runtime**. Is it possible the client ID is unset / wrong when you're running i3bar? How do you specify the environment variables when running i3?

**Comment by danihodovic** [comment]
```
$ cat .envrc
export GOOGLE_CLIENT_ID=X
export GOOGLE_CLIENT_SECRET=Y

$ echo $GOOGLE_CLIENT__ID
X

$ my_barista setup-oauth
```

During i3 runtime the variables are not set in the environment, only when configuring OAuth.

**Comment by soumya92** [comment]
> During i3 runtime the variables are not set in the environment

The client ID needs to exist for both the setup process as well as actually using the saved credentials. The best way to add it would be using something similar to the [build script](https://github.com/soumya92/barista/blob/master/build.sh), where the environment variables are taken at *build* time and baked into the binary.

Failing that, you will need some way to provide the env vars to the running bar, so maybe even just sourcing envrc would work, e.g.
```
status_command "source ~/.envrc; exec my_barista"
```
(I haven't tested this though, so it might not work).
