### ISSUE TITLE
Add a screenshot to the README

### ISSUE THREAD

**Issue by davidv171** [soumya92/barista#76]
A screenshot of an example bar would be great. Maybe a config for it added somewhere in the repo. Users could submit their own screenshots, and link to their dotfiles in the README.

**Comment by soumya92** [comment]
What about using the wiki? I deleted the wiki when I moved to GH pages, but I can bring it back to show examples and screenshots.

**Comment by soumya92** [comment]
Wiki has been reactivated, feel free to edit to add examples/screenshots.
