### ISSUE TITLE
Left aligned modules

### ISSUE THREAD

**Issue by binaryplease** [soumya92/barista#79]
Hi, is it possible to left-align modules? I'd like to have some modules show at the right side (normal) and some on the left.

Also is ther a way to style the workspace indicator in i3?

**Comment by soumya92** [comment]
> Hi, is it possible to left-align modules? I'd like to have some modules show at the right side (normal) and some on the left.

Needs i3bar support. If i3bar adds spacer support, then this would be fairly easy to implement. There was a proposal at some point (https://github.com/i3/i3/issues/1148#issuecomment-301039599), but I don't know what happened beyond that.

> Also is ther a way to style the workspace indicator in i3?

Do you just mean the colours and fonts? You should be able to change those in your i3 config: https://i3wm.org/docs/4.7/userguide.html#_colors
