### ISSUE TITLE
Cannot compile volume module if alsa headers are not installed

### ISSUE THREAD

**Issue by erizocosmico** [soumya92/barista#87]
Hi there!

If alsa headers are not installed, it's impossible to compile the whole volume mode even if you're only using it for pulse audio due to https://github.com/soumya92/barista/blob/master/modules/volume/alsa.go#L17-L20

It would be nice if the package was split into `barista.run/modules/volume/alsa` and `barista.run/modules/volume/pulseaudio` so you don't need the alsa headers to use pulse audio.

I can totally make a PR with the necessary changes for this if you're ok with the idea of splitting the packages.

**Comment by soumya92** [comment]
Sounds good to me. I would gladly accept a pull request making this change. Thanks!
