### ISSUE TITLE
Docs / Customising Barista: curling the sample mybar.go file downloads HTML

### ISSUE THREAD

**Issue by wjdp** [soumya92/barista#89]
On https://barista.run/docs/customising running `curl -L https://git.io/fxw62 -o mybar.go` downloads an HTML file rather than a go file.

Visiting https://git.io/fxw62 in browser redirects (same as curl) to https://github.com/soumya92/barista/blob/master/samples/simple/simple.go, curling that gives the same HTML.

Using https://raw.githubusercontent.com/soumya92/barista/master/samples/simple/simple.go instead works (less pretty URL though :smile: )

![image](https://user-images.githubusercontent.com/1690934/70572631-0faa0100-1b98-11ea-840d-dbfe0bb7dc3e.png)

**Comment by soumya92** [comment]
Wow. I thought I tested that. Fixed, new shortlink is https://git.io/Je90h.
