### ISSUE TITLE
*nl.NetlinkSocket does not implement nlReceiver (wrong type for Receive method)

### ISSUE THREAD

**Issue by fruitloop** [soumya92/barista#90]
Hi,
on my machine I get the following error when I import `barista.run/modules/netinfo`:

```
../../go/src/barista.run/base/watchers/netlink/nl.go:82:2: cannot use *nl.NetlinkSocket value as type nlReceiver in return argument:
      *nl.NetlinkSocket does not implement nlReceiver (wrong type for Receive method)
          have Receive() ([]syscall.NetlinkMessage, *unix.SockaddrNetlink, error)
          want Receive() ([]syscall.NetlinkMessage, error)
```

**Comment by soumya92** [comment]
Most likely your local copy of netlink is out of date. I was hoping that the `go.mod` file would fix this problem, but I guess my expectations were too high.

I think if you just update netlink: `go get -u github.com/vishvananda/netlink/nl`, this will be fixed.

**Comment by JeffHenson** [comment]
I've seen the same message and forcing github.com/vishvananda/netlink to v1.0.0 fixes it for me. It appears that v1.1.0 of netlink broke semantic versioning and is not compatible with v1.0.0.

**Comment by soumya92** [comment]
Thanks for the pointer. I will update the code and go.mod to be 1.1.0, and hopefully that will also fix the problem for non-go.mod cases.
